name: Build & Deploy
on: 
  push:
    tags:
      - '**'
  workflow_dispatch: 

jobs: 
  build-deploy:
    name: Build & Deploy
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update & Install Prequisities
        run: |
          docker pull emscripten/emsdk
          docker run -di --name emscripten -v $(pwd):/src emscripten/emsdk bash
          docker exec -i emscripten apt update
          docker exec -i emscripten apt -y install autoconf libtool dh-autoreconf pkg-config
      - name: Build libyara
        run: docker exec -i emscripten /bin/sh -c 'rm -rf build && mkdir -p build && cd build && emcmake cmake -S .. -B . && emmake make'
      - name: Deploy to NPM
        if: github.event_name == 'push' && startsWith('refs/tags/v', github.ref)
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish || true
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Cleanup
        if: always()
        run: docker rm -f emscripten
